apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    # When can have multiple labels
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        # when the POD is created, this is the port to access the container
        - containerPort: 80