apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    # If we just define
    # - port: 80
    # we will listen and dispatch everything to port 80
    # ------
    # If we want to listen on one port and dispatch to another:
    # - port: 9000 # Listen
    #   targetPort: 80 # Dispatch
    - port: 9000
      targetPort: 80