apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80
      # We can define nodePort with this range:
      # nodePort: 30000-32767
      nodePort: 30000
  selector:
    app: primeiro-pod