apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-backup-db
spec:
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12)
  # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  # │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  # │ │ │ │ │ 
  # │ │ │ │ │
  # * * * * *
  # schedule: "* * * * *"
  schedule: "0 3 * * *"
  # schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            # The sql file is being copied to the 'carlohcs/mysqldump` container itself. Not for the volume
            # It's needed to implement a different approach
            # Or make an upload to some place
            image: carlohcs/mysqldump:v3
            env:
              - name: MYSQL_ENV_DB_USER
                valueFrom:
                  secretKeyRef:
                    name: secret-vollmed
                    key: MYSQL_ENV_DB_USER
              - name: MYSQL_ENV_DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: secret-vollmed
                    key: DB_PASSWORD
              - name: MYSQL_ENV_DB_HOST
                valueFrom:
                    configMapKeyRef:
                      name: config-map-vollmed
                      key: DB_HOST
            # In theory, this should be enough
            # https://stackoverflow.com/questions/47664107/docker-mount-to-folder-overriding-content
            volumeMounts:
              - name: mysql-volume-disk
                mountPath: /mysqldump
          restartPolicy: OnFailure
          volumes:
            - name: mysql-volume-disk
              persistentVolumeClaim:
                claimName: pvc-mysql-vollmed
