apiVersion: v1
kind: Service
metadata:
  name: svc-mysql-vollmed
  labels:
    app: svc-mysql-vollmed
spec:
  ports:
  - port: 3306
    name: svc-mysql-vollmed
  clusterIP: None
  selector:
    app: svc-mysql-vollmed