apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-pod
  labels:
    app: pod-secret-pod
spec:
  containers:
    - name: pod-secret-pod-container
      image: svenstaro/miniserve
      ports:
        - containerPort: 3301
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      envFrom:
        - secretRef:
            name: secret-opaque-example-custom-variable
      
