# https://www.mirantis.com/cloud-native-concepts/getting-started-with-kubernetes/what-are-kubernetes-secrets/
# username: echo -n 'admin' | base64
# password: echo -n '1f2d1e2e67df' | base64
# https://medium.com/@rajeshmamuddu/kubernetes-secrets-0e4a6413ac69
apiVersion: v1
kind: Secret
metadata:
  name: secret-opaque-example-custom-variable
type: Opaque
stringData:
  MINI_SERVE_SPA: 'true'
  MINISERVE_COLOR_SCHEME: 'monokai'
  MINISERVE_PATH: '.'
  MINISERVE_PORT: '3001'