apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-system-deployment
spec:
  template:
    metadata:
      name: news-system-data
      labels:
        app: news-system-data
    spec:
      containers:
        - name: news-system-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef: 
              name: system-configmap
  replicas: 1
  selector:
    matchLabels:
      app: news-system-data