apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-portal-deployment
# spec:
  # containers:
  #   - name: news-portal-container
  #     image: aluracursos/portal-noticias:1
  #     ports:
  #       - containerPort: 80
  #     envFrom:
  #       - configMapRef:
  #           name: news-portal-configmap
spec:
  template:
    metadata:
      name: news-portal
      labels: 
        app: news-portal
    spec:
      containers:
        - name: news-portal-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-portal-configmap
          # Tell us if the application is still alive
          # And when it should be restarted
          livenessProbe:
            httpGet:
              path: /
              port: 80
            # Frequency
            periodSeconds: 10
            # Limit of failures
            failureThreshold: 3
            # Wait for the initial container running
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            # Frequency
            periodSeconds: 10
            # Limit of failures
            failureThreshold: 5
            # Wait for the initial container running
            initialDelaySeconds: 3
          # Needed to do the autoscaling
          resources:
            requests:
              cpu: 10m
  replicas: 3
  # Kubernetes doesn't know which template it should follow
  # Even being in the same file like we have here
  # so we need to define the selector as well
  # to have the same name as defined before
  # eg.: news-portal (label defined on top)
  selector:
    matchLabels:
      app: news-portal
