apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-pvc-disk-with-storage-class
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fake-gcp-storage-class
