apiVersion: v1
kind: Pod
metadata:
  name: fake-pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-inside-of-container
          name: fake-pod-pv-disk
  volumes:
    - name: fake-pod-pv-disk
      persistentVolumeClaim:
        # Same name from `fake-pvc-disk`
        claimName: fake-pvc-disk