apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-pvc-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: local-storage / when we need to map our local file inside at the container (for development)
  # storageClassName: local-storage-db / when we need to map a database
  storageClassName: standard
