apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
	name: fake-gcp-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
	type: pd-standard
	fstype: ext4
  # Default value
	# replication-type: none