apiVersion: v1
kind: Pod
metadata:
  name: news-system-data
  labels:
    app: news-system-data
spec:
  containers:
    - name: news-system-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
      - configMapRef: 
          name: system-configmap
