apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-news-system
spec:
  replicas: 1
  template:
    metadata:
      name: news-system-data
      labels:
        app: news-system-data
    spec:
      containers:
        - name: system-news-containers
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: system-configmap
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /tmp
          # Tell us if the application is still alive
          # And when it should be restarted
          livenessProbe:
            httpGet:
              path: /
              port: 80
            # Frequency
            periodSeconds: 10
            # Limit of failures
            failureThreshold: 3
            # Wait for the initial container running
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            # Frequency
            periodSeconds: 10
            # Limit of failures
            failureThreshold: 5
            # Wait for the initial container running
            initialDelaySeconds: 3
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: image-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
  selector:
    matchLabels:
      app: news-system-data
  serviceName: svc-system-data